# Все наши изменения в репе https://github.com/lokha/NoteBlockAPI
name: ${name}

main: ${mainClass}
version: ${version}

api-version: 1.13

description: a developer interface to play nbs-files ingame
authors: [xxmicloxx, michidk, koca2000, Luck]